### ISSUE TITLE
Correlograms normalization

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#151]
Allow to switch between uniform normalization and per-row normalization.

**Comment by nippoo** [comment]
@nsteinme do you need this? Or is a single type of normalisation - as currently implemented - okay?

**Comment by nsteinme** [comment]
It was a thing I used from time to time in KV, since sometimes one cluster
has very many more spikes than another and the default normalization
doesn't allow you to see the CCG of the sparsely-firing one well. This
would become still more of an issue for longer and longer recordings (since
you will be able to cluster even sparser-firing ones). So I vote for
including it, if it isn't too much of a pain.

Nick

**Comment by rossant** [comment]
this one is done too!
