### ISSUE TITLE
Improved similarity measure

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#273]
https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/session.py#L654

**Comment by rossant** [comment]
@nippoo can you remind me what was the new algo discussed over skype?

**Comment by rossant** [comment]
session:346

```
            mu_0 = self.cluster_store.mean_features(target)
            mu_1 = self.cluster_store.mean_features(candidate)

            omeg_0 = self.cluster_store.mean_masks(target)
            omeg_1 = self.cluster_store.mean_masks(candidate)

            omeg_0 = np.repeat(omeg_0, self.model.n_features_per_channel)
            omeg_1 = np.repeat(omeg_1, self.model.n_features_per_channel)

            d_0 = np.dot(mu_0, omeg_0)
            d_1 = np.dot(mu_1, omeg_1)

            return (d_0 - d_1) ** 2
```

just tried: weird results. TBI...

**Comment by nippoo** [comment]
Ah okay, we want:

```
   d_0 = np.dot(mu_0, omeg_0)
   d_1 = np.dot(mu_1, omeg_1)
   
   return np.linalg.norm(d_0 - d_1)
```

**Comment by nippoo** [comment]
`np.multiply` is the [Hadamard product](http://en.wikipedia.org/wiki/Hadamard_product_(matrices)).

**Comment by rossant** [comment]
you can also just use `mu_0 * omeg_0`

**Comment by nippoo** [comment]
ugh I'd always assumed that was the dot-product. This all makes sense now...

**Comment by rossant** [comment]
yeah in matlab that's the case! (i think...)

**Comment by rossant** [comment]
seems to work fine with your suggestion @nippoo ! will be closed in the next PR

**Comment by nsteinme** [comment]
For most clusters it looks like I get good results for closest match. But for this one cluster I had to scroll through something like 100 (not exaggerating) "closest match"es that looked like these:
![image](https://cloud.githubusercontent.com/assets/7590975/8213535/57690222-151a-11e5-9164-0dd466d19d59.png)

![image](https://cloud.githubusercontent.com/assets/7590975/8213539/62e732cc-151a-11e5-9a05-ae13b6fb6fe0.png)

before finally getting to this: 
![image](https://cloud.githubusercontent.com/assets/7590975/8213517/3cf9fd56-151a-11e5-98a5-e203fedc5df6.png)

which isn't an exact match but it's way closer than anything else. Any ideas why this would happen? The cluster doesn't look unique to me; other ones on the same channels do fine. Anyway, I don't think this is worth acting on if you don't have any ideas, since it seems to work fine for the rest of the clusters. But it can be logged here, anyway, in case we start to observe other ones in the future...

**Comment by rossant** [comment]
the second cluster looks quite noisy no? in any case, yes please put the filename and cluster numbers here so that I (or @nippoo) can take a look

**Comment by nsteinme** [comment]
Data in \\zserver\multichanspikes\M141003_NS2ROSS\20141112\20141112_all.kwik, cluster #17.

I don't think it is particularly noisier than any other cluster. These channels are a little raggedy-looking mostly because that section of the probe was very highly active.

**Comment by rossant** [comment]
I won't have time to check this right now -- let me know if you do @nippoo

**Comment by rossant** [comment]
@nsteinme is this bug critical, or can we set it to the v0.3.0 milestone?

**Comment by nsteinme** [comment]
Not critical, or especially not until/unless I see it again in another
example.

**Comment by nsteinme** [comment]
Ok, I would like to "re-up" this issue. I have now observed more examples of this. Somehow it prefers to give you a "most similar" cluster that has *nothing* on the channels that the "best unsorted" cluster inhabits, rather than give you ones that are on the same channels but are a bit different. It may to do with the fact that there is no normalization - so a unit with big overlapping features looks potentially "more distant" than one with *zero* overlapping features. 

Can we move this back to 0.3.0? I think it is a big problem.

**Comment by rossant** [comment]
Can you try custom measures and propose one that works better for you?

**Comment by nsteinme** [comment]
You think it will work? custom quality function doesn't work.
https://github.com/kwikteam/phy/issues/627

**Comment by rossant** [comment]
I will have a look, in the meantime maybe you can try to change the code
directly in the source?

**Comment by nsteinme** [comment]
K, I will talk with Kenneth then try something.

**Comment by nsteinme** [comment]
Hey, I talked with Kenneth and we came up with some things to try. It may take a while for me to try them though because I have to find good test cases. Could you assign this issue to me, though? I can do it.
