### ISSUE TITLE
Crash when no KWX

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#293]

**Comment by rossant** [comment]
done: it will use default masks (1) and features (0) in this case, with a warning
note to self: in this case, the feature view might be slow on low end gpu, because there are many points overlapping at 0 with transparency and complex fragment shader (see #201). Possible fixes:

* do not show the feature view in this case
* switch to low quality features
* just display 0 or 1 spikes instead of 10k spikes at the same position

**Comment by nippoo** [comment]
Uh. Can't you just plot a single point at [0, 0, 0, ..., 0] in the view? Why do you need to plot all the points?

**Comment by rossant** [comment]
there is no need to! it's just the way it is architectured now... it will be easier to fix after #296
