### ISSUE TITLE
Better handling of raw data

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#437]
```
is there a path specified in the recordings[n]/raw/hdf5_path?
does it exist?
return(HDF5 file attribute)
is there a .dat or .bin of the same basename in the same path? (not sure how we deal with multiple recordings but k
return(.dat/bin)
is there a .raw.kwd of the same basename in the same path?
return(raw.kwd)
basically priority 1) hdf5 link 2) .dat/bin 3) .raw.kwd
```

**Comment by nippoo** [comment]
The logic (inc #488) should be:

- is there a path specified in the recordings[n]/raw/hdf5_path?
- does this path exist? __if so, return it__
- if not, does a file with the same name exist in the same directory as the kwik file? __if so, return it___
- is there a .dat or .bin of the same basename in the same path? __if so, return it (maybe we will remove this because of complexities with multiple .dats!__
- is there a .raw.kwd of the same basename in the same path? __if so, return it__
