### ISSUE TITLE
CLI command to visualize raw data with spikes

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#459]
For example, `phy traces myfile.dat --n-channels=120 --spike-samples=myspikes.txt`

(other formats like `.npy` or `.kwik` can also be supported for the spikes)

Requires #458 and #427.

**Comment by nsteinme** [comment]
And as a really useful extension, could it try to perform spike detection on just the segment you're looking at and highlight the spikes? It could be a smaller/simpler version of detection, since you just need the masks really.

As an extension on that, snippets to change the detection parameters, with immediate re-detection of the viewed segment?

Ideally it would incorporate a way to jump around the file, e.g. with a snippet.
