### ISSUE TITLE
Create a main trivial clustering at the end of spike detection

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#566]

**Comment by nsteinme** [comment]
And fill the kwx file at that time, please. For compatibility with old code. If you want it could be an option, like --makeKwx True.

**Comment by nsteinme** [comment]
If this is any different, should make the kwx also if you just do "phy detect" instead of phy spikesort - currently the kwx is produced with features_masks but not with waveforms. I'm probably being backwards but I don't have yet anything written to load the waveforms dynamically like you do in phy...
